// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: mp-health
:page-layout: guide
:page-duration: 20 minutes
:page-description: Learn how to use MicroProfile Health API in an application
:page-tags: ['HealthCheck' , 'MicroProfile' , 'REST']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Adding health reporting to a microservice

Learn how to provide and check the health of a microservice using MicroProfile Health.

// =================================================================================================
//  What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to add Microprofile health check to report the health of
a RESTful service. The great benefit from adding a health check is that it helps in machine to
machine communications, monitoring and knowing which services are performing in the application.

A health check is a method for assessing the state of RESTful service to know the overall
application performance. The state of a RESTful service is either `UP` or `DOWN`.
When the state is `UP`, the service is currently available. However, when it is `DOWN`, the service
is currently not available (i.e. on maintenance).

The health endpoint reports the state of all the services in an application. If all services are
`UP`, the health endpoint responds with `200` code indicating that the health outcome is `UP`.
If any service is `DOWN`, the health endpoint responds with `503` code indicating that
the health outcome is `DOWN`.

You will add a health check to report the states of `InventoryResource` and `PropertiesResource`
RESTful services. Then you will write tests to validate the states of these services. These two
services are provided for you in this guide. If you want to learn how to create these services, read
https://github.com/OpenLiberty/draft-guide-rest-cdi[Creating a RESTful web service with contexts and dependency injection].

You can find the endpoints for the two services at:
```
http://localhost:9080/system/properties
```
```
http://localhost:9080/inventory/hosts
```
You can also find the health endpoint which contains the outcome of the states of the two services
above at:
```
http://localhost:9080/health
```

// =================================================================================================
// Getting Started
// =================================================================================================

// include::{common-includes}/gitclone.adoc[]

== Getting started

The fastest way to work through this guide is to clone the git repository and use the starting project
that is provided in the `start` directory. To do this, run the following commands:

[subs="attributes"]
----
git clone https://github.com/openliberty/guide-mp-health.git
cd guide-mp-health/start
----

// =================================================================================================
// Try what you'll build
// =================================================================================================

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished inventory application with
Microprofile Health API implemented. Feel free to give it a try before you proceed with building your own.

To try out the application, first navigate to the `finish` directory and then execute the following
Maven goals to build the application and run it inside Open Liberty:

```
mvn install liberty:start-server
```

Point your browser to `\http://localhost:9080/health`. From here, you can see the health of the
two services. As shown, there are two checks. One that shows the state of `InventoryResource` and
the other which shows the state of `PropertiesResource`. They are both in `UP` state as you may
expect and because of that the overall outcome is `UP`. You can verify that by pointing to one of the
services.

Once you are done checking out the application, stop the Open Liberty server:

```
mvn liberty:stop-server
```

Now, navigate back to the `start` directory to begin.

// =================================================================================================
// Adding health check to inventory application
// =================================================================================================

== Adding health check to inventory application

Begin by enabling the MicroProfile Health feature in your `pom.xml` file. This feature allows you to
use the MicroProfile Health API to provide health checks to your RESTful services.

Navigate to the start/pom.xml file and add the required dependency:

[source, xml, indent=0]
----
include::finish/pom.xml[tags=health]
----

Proceed with the two sections below to add health checks to `PropertiesResource` and
`InventoryResource` services.

// =================================================================================================
// Adding health check to PropertiesResource service
// =================================================================================================

=== Adding health check to PropertiesResource service

Create `PropertiesHealth.java` class in `/start/src/main/java/io/openliberty/guides/system/`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/system/PropertiesHealth.java[tags=PropertiesHealth]
----

The `org.eclipse.microprofile` package contains the related Microprofile Health classes.

The `@Health` annotation indicates that this class will be read for reporting the state of
a desired service to `/health` endpoint. The `@ApplicationScoped` annotation is
required because the service must stay active within the lifetime of the application for the
state to be reported.

The `HealthCheck` interface is implemented by the class which means you must override `call()`
method from this interface.

The state of the `PropertiesResource` service is simulated by reading the system property of the
host. If the system property `wlp.server.name` is `defaultServer`, then the state is `UP`, otherwise, it
is `DOWN`.

In addition, you need to pass the service name `PropertiesResource` as an argument to the `named()`
method to indicate that this is the service being reported.

// =================================================================================================
// Adding health check to InventoryResource service
// =================================================================================================

=== Adding health check to InventoryResource service

Create a class `InventoryHealth.java` in `/start/src/main/java/io/openliberty/guides/inventory/`.

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryHealth.java[tags=InventoryHealth]
----

This service reports its state depending on two things:

1. A property of type boolean found in `/start/CustomConfigSource.json`:

    "io.openliberty.guides.microprofile.inventory.inMaintenance": false


[TIP]
    This property in the file is provided for you in this guide.
    If you want to learn how to configure this file, read
    https://github.com/OpenLiberty/draft-guide-microprofile-config[Configuring Microservices using MicroProfile Config].
    You will use this file to manipulate on the state of the service. The way to read this file is by
    creating an `InventoryConfig` object which will do that for you. [fix indentation]

2. `PropertiesResource` service availability (i.e. returns 200 response code).

As you can see, adding health check to this class is quite similar as in the previous section above.
However, there are minor adjustments and additions.

The `@Inject` annotation is used to initialize the `InventoryConfig` object. This object will allow
you to read that property in `CustomConfigSource.json` file. You can read more about `@Inject` from
https://github.com/OpenLiberty/draft-guide-rest-cdi[Creating a RESTful web service with contexts and dependency injection].

The `isHealthy()` method returns a boolean that decides the state of `InventoryResource`.
It does the two things that were mentions above.

The `isHealthy()` method is used as the condition in `call()` method. The state of
`InventoryResource` service is `UP` if `isHealthy` returns `true` and vice versa.

Now, open `InventoryResource` in `/start/src/main/java/io/openliberty/guides/inventory/`

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[tags=InventoryResource]
----

The service is supposed to show the system properties for a hostname through calling
`getPropertiesForHost()` method. This can only happen if the condition `config.isInMaintenance()`
is evaluated to `false`. Otherwise the service responds with a maintenance message.

The condition `config.isInMaintenance()` is the key here. The `isHealthy()` method in `InventoryHealth`
class is also using that condition to report the state of `InventoryResource` service.

This is the same for `listContents()` method which lists the stored hosts.

The point from here is to make the service responds based on its state. When it is `UP`,
it functions normally. When it is `DOWN`, it responds with a maintenance message.

The `serviceInMaintenance()` method from the imported class `JsonMessages` is already provided for
you to be used in this guide. To learn more about this class, read
https://github.com/OpenLiberty/draft-guide-microprofile-config[Configuring Microservices using MicroProfile Config].
This method in this class just respond with a `JsonObject` containing a message telling the user
that the service is currently on maintenance. You just need to pass the name of the service to it.

// =================================================================================================
// Building and running the application
// =================================================================================================

== Building and running the application

To build the application, run the Maven install goal from the command line:

  mvn install

This goal builds the application and creates a .war file in the target directory. The goal also
configures and installs Open Liberty into the target/liberty/wlp directory.

Next, run the Maven liberty:start-server goal:

  mvn liberty:start-server

This goal starts an Open Liberty server instance. Your Maven pom.xml is already configured to
start the application in this server instance.

Once the server is running, you can find the health endpoint
reporting the state of the two services at the following URL:

* `\http://localhost:9080/health`

Now, try to make the `InventoryResource` service in maintenance (i.e. temporarily down) by changing the
property `io_openliberty_guides_inventory_inMaintenance` value to `true` found under
`/finish/CustomConfigSource.json`. Refresh the browser. You will see the state of the
`InventoryResource` is currently `DOWN` and because of that the overall outcome is `DOWN`. You can
verify that by point your browser to inventory service. As you can see, the service is responding
with a message telling you that it is in maintenance.

If you make changes to the code, use the Maven package goal to rebuild the application and have
the running Open Liberty server pick them up automatically:

  mvn package

To stop the Open Liberty server, run the Maven liberty:stop-server goal:

  mvn liberty:stop-server

// =================================================================================================
// Testing Services States
// =================================================================================================

== Testing Services States

You will write two test methods `testIfServicesStatesUp()` and `testIfInventoryTemporarilyDown()` to
validate the state of `PropertiesResource` and `InventoryResource` services. You will also use a
test helper class `HealthTestUtil` that is already provided for you to perform these two tests.

Begin by creating a test class src/test/java/it/io/openliberty/guides/health/HealthTest.java:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/health/HealthTest.java[tags=HealthTest]
----

The @Before and @After annotations are placed on methods that execute before and after every test
case. These methods are generally used to perform any setup and teardown tasks.
In this case, the `setup()` method initializes the fields. they are the `JsonArray` that hold the states
of the services, the two maps for storing the states when the services are up and when they are
down and the constant to hold the property that will be read. `The teardown()` method simply resets
the property's value.

There are few test case methods annotated with `@Test` to test the functionality of the inventory
application after adding health checks.

* The `testIfServicesStatesUp()` method checks if both services are currently `UP` using
`checkServicesStates()` method which verifies and asserts the actual states of both services. This
test is using these helper methods:

    *** `connectToHealthEnpoint()` method: sends a request to `\http://localhost:9080/health` then
    checks the `200` response code and reads the response as `JsonArray` which contains the states
    of the two services

    *** `getActualState()` method: returns the state (`UP` or `DOWN`) of a specific service
    from the `JsonArray` object that is passed as an argument to it.

* The `testIfInventoryTemporarilyDown()` method follows the same procedure as in the previous test
case. However, it sends another request after changing the property's value, `inMaintenance`, from
`false` to `true` . Then it validates the state of the service `InventoryResource` by asserting if
it is `DOWN` and the other service is `UP`.

=== Running the tests

Go to `start` directory and run `mvn clean install`. You should see two tests pass with the following
results:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.microprofile.HealthTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.912 sec - in it.io.openliberty.guides.microprofile.HealthTest

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
```

// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You have learned how to add a health check to report the states of microservices such as REST in an
application. Then you wrote tests to validate that.

include::{common-includes}/finish.adoc[]
