// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: mp-health
:page-layout: guide
:page-duration: 20 minutes
:page-description: Learn how to use MicroProfile Health API in an application
:page-tags: ['HealthCheck' , 'MicroProfile' , `CDI`, `@Health`, `Config` ,`ConfigProperty`,'REST']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Adding health reporting to a microservice

Learn how to provide and check the health of a microservice using MicroProfile Health.

// =================================================================================================
//  What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to use MicroProfile Health feature to report the health of
a RESTful application. The great benefit from adding a health check is that it allows your RESTful
service to participate in the decision making process about its health.

The MicroProfile Health feature provides an endpoint that you can get the health check results as a
JSON object. This HTTP request endpoint returns a status code of `200` if the application outcome
is `UP`, otherwise, a status code of `503` if it is `DOWN`.

The health check is used to assess the state of a service in an application. The state of a service
is either `UP` or `DOWN`. When the state is `UP`, the service is available. However,
when it is `DOWN`, the service is currently not available (or in maintenance).
The overall outcome of the application is `UP` only when the checks of all the services are `UP`.
It is important to note that a `DOWN` result can be used by a service orchestrator to drive decisions
about when to replace an instance of a service.

Before the service reports its state, it should check what it has to be available. Depending on
what the service has or what is provided to it, it can report whether it is healthy or not
via the Microprofile Health API implementation. A self check can be anything related to the
service. It could be a dependency, a successful connection to an endpoint, availability 
of resources (e.g. a database), a system property and many others.

You will add health checks to report the states of the `system` and `inventory`
RESTful services in an inventory manager application. This application and the two services in it
are provided for you in this guide. If you want to learn how to create a RESTful application, see
https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service].

After starting the application, you will be able to access two microservices to test their availability:

* `http://localhost:9080/system/properties` retrieves the information for a specific host

* `http://localhost:9080/inventory/systems` retrieves the information for a list of all previously registered hosts

// =================================================================================================
// Getting Started
// =================================================================================================

== Getting started

The fastest way to work through this guide is to clone the Git repository and use the starting project
that is provided in the `start` directory. To do this, run the following commands:

[subs="attributes"]
----
git clone https://github.com/OpenLiberty/draft-guide-microprofile-health.git
cd draft-guide-microprofile-health/start
----

// =================================================================================================
// Try what you'll build
// =================================================================================================

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished
health check implementation for the services in the application. Feel free to give it a try before
you proceed with building your own.

To try out the application, first navigate to the `finish` directory and then execute the following
Maven goals to build the application and run it inside Open Liberty:

```
mvn install liberty:start-server
```

Point your browser to MicroProfile Health Check endpoint: `http://localhost:9080/health`. From
here, you can see the health of the two services as well as the overall health outcome of the
application. As shown, there are two checks. One that shows the state of `system`
service and the other shows the state of `inventory` service. They are both in `UP` state
as you may expect and because of that the overall outcome of the application is `UP`.

Once you are done checking out the application, stop the Open Liberty server:

```
mvn liberty:stop-server
```

Now, navigate back to the `start` directory to begin.

// =================================================================================================
// Adding health check to RESTful services
// =================================================================================================

== Adding health check to RESTful services

Begin by navigating to the `pom.xml` file to check the required dependency. The `microprofile-health-api` 
dependency has been added for you in the `start/pom.xml` file. This dependency allows you to
use the MicroProfile Health API to provide health checks to your RESTful services.
The `mpHealth-1.0` feature has been also enabled in the `start/src/main/liberty/config/server.xml` file. 
This feature provides `/health` endpoint to your application.

Proceed with the two sections below to add health checks to `system` and `inventory` services.

// =================================================================================================
// Adding health check to system service
// =================================================================================================

=== Adding health check to system service

Create the class `/start/src/main/java/io/openliberty/guides/system/SystemHealth.java`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/system/SystemHealth.java[tags=SystemHealth]
----

The `org.eclipse.microprofile` package contains the required MicroProfile Health Check classes.

The `@Health` annotation indicates that this class will be read for reporting the state of
a desired service to `http://localhost:9080/health`. The `@ApplicationScoped` annotation is
required because the health check service must stay active within the lifetime of the application
for the state to be reported.

This class implements the `HealthCheck` interface, which means you must override the `call()`
method from this interface.

The `system` service should do a self check. As you can see, it is reporting its healthy state
by reading the system property of the host. If the system property `wlp.server.name` is
`defaultServer`, then the state is `UP`, otherwise, it is `DOWN`.

Lastly, you need to pass the service name `system` as an argument to the `named()`
method to indicate that this is the service being reported.

// =================================================================================================
// Adding health check to inventory service
// =================================================================================================

=== Adding health check to inventory service

Create the class `/start/src/main/java/io/openliberty/guides/inventory/InventoryHealth.java`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryHealth.java[tags=InventoryHealth]
----

This service reports its healthy state depending on two things:

1. A property of type boolean found in `/start/CustomConfigSource.json`. The property in this
file is used to manipulate on the state of the service. This file is provided for you in this guide and
if you want to learn how to configure it, see
https://openliberty.io/guides/microprofile-config-intro.html[Configuring Microservices using MicroProfile Config].

    "io.openliberty.guides.microprofile.inventory.inMaintenance": false

2. `system` service availability (i.e. returns 200 response code).

As you can see, adding health check to this service is similar as in the previous section above.
However, there are minor adjustments and additions.

The `@Inject` annotation is used to initialize the `InventoryConfig` object. This object will allow
you to read the property in the `CustomConfigSource.json` file. You can learn more about the
`@Inject` annotation from
https://openliberty.io/guides/rest-intro.html[Handling dependencies with RESTful web services].

The `isHealthy()` method returns a boolean that determines the health of `inventory` service.
It checkes the two conditions that were mentioned above. This method is used as the condition in
`call()` method. The state of `inventory` service is `UP` if isHealthy returns `true` and `DOWN` 
if isHealthy returns `false`.

Now, open `inventory` service from `/start/src/main/java/io/openliberty/guides/inventory/InventoryResource`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[tags=InventoryResource]
----

The service invokes `getPropertiesForHost()` method to display
the system properties for a hostname. This can only happen if
`io.openliberty.guides.microprofile.inventory.inMaintenance` configuration is set to `false`.
Otherwise the service responds with the message `Service is currently in maintenance` and also
a `503` response code. If the service displays the system properties as desired, then
the health of this service is `UP`. If the service is down for maintenance, then its health is
`DOWN'. Notice the second condition in the `isHealthy()` method of the `InventoryHealth` class
is relying on this setting.

The same condition is applied for the `listContents()` method in this service. This method lists
the stored hosts.

// =================================================================================================
// Building and running the application
// =================================================================================================

== Building and running the application

To build the application, run the Maven install goal from the command line:

  mvn install

This goal builds the application and creates a .war file in the target directory. The goal also
configures and installs Open Liberty into the target/liberty/wlp directory.

Next, run the Maven liberty:start-server goal:

  mvn liberty:start-server

This goal starts an Open Liberty server instance. Your Maven pom.xml is already configured to
start the application in this server instance.

Once the server is running, you can find the health endpoint
reporting the state of the two services at the following URL:

* `http://localhost:9080/health`

Now, try to turn the `inventory` service down (i.e. in maintenance) by changing the
property `io_openliberty_guides_inventory_inMaintenance` value to `true`. This property is found in
`/resources/CustomConfigSource.json`. Refresh the browser. You will see the state of the
`inventory` is currently `DOWN` and because of that the overall outcome is `DOWN`. You can
verify that by pointing your browser to the inventory service
`http://localhost:9080/inventory/systems`. As you can see, the service
is responding with a message telling you that it is in maintenance.

If you make changes to the code, use the Maven package goal to rebuild the application and have
the running Open Liberty server pick them up automatically:

  mvn package

To stop the Open Liberty server, run the Maven liberty:stop-server goal:

  mvn liberty:stop-server

// =================================================================================================
// Testing health check
// =================================================================================================

== Testing health check

You will write two test methods `testIfServicesAreUp()` and `testIfInventoryServiceIsDown()` to
validate the state of the Inventory Manager Application among with the `system` and
`inventory` services.

Begin by creating a test class `start/src/test/java/it/io/openliberty/guides/health/HealthTest.java`:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/health/HealthTest.java[tags=HealthTest]
----

The `static` keyword with curly brackets is used to initialize the static fields such as the
`JsonArray` field that hold the states of the services, the two maps for storing the states when the
services are up and when they are down, and the constant to hold the property that will be read.

The `@After` annotation is placed on methods that execute after every test case. These methods are
generally used to perform any teardown tasks. In this case, the `teardown()` method simply resets
the property's value.

There are few test case methods annotated with `@Test` to test the functionality of the inventory
application after adding health checks.

* The `testIfServicesAreUp()` method sends a request to `http://localhost:9080/health` then it
verifies the `200` response code is returned. After that, it calls the `connectToHealthEndpoint()` helper method
to read the response as `JsonArray` which contains the actual states of the two services. Then, this
`JsonArray` is passed to `checkServicesStates()` method which compares and asserts the `JsonArray`
with the expected services states. This method uses the helper method `getActualState()` to return
the actual state of each service from this `JsonArray`. The expected state for both of the services in
this test is `UP`.

* The `testIfInventoryServiceIsDown()` method follows a similar procedure as in the previous test
case. It first checks if the services' states are `UP`. Next, the
`io.openliberty.guides.microprofile.inventory.inMaintenance` property value is changed from
`false` to `true` in the `CustomConfigSource.json` file. With the property update, we send a
request to check the services' states again. This time the expected response code should be 503.
Lastly, we assert if the state of the `inventory` service is `DOWN` and the state of 
`system` service is `UP`.

=== Running the tests

Go to `start` directory and run `mvn clean install`. You should see two tests pass with the
following results:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.health.HealthTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.21 sec - in it.io.openliberty.guides.health.HealthTest
Running it.io.openliberty.guides.inventory.EndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.169 sec - in it.io.openliberty.guides.inventory.EndpointTest

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
```

To see whether the tests detect a failure, change the values of the tests maps inside the `static` curly brackets.
Re-run the Maven build. You will see a test failure occur.

// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You have learned how to add health checks to report the states of microservices in an
application. Then you wrote tests to validate that.

Feel free to try one of the related MicroProfile guides. They demonstrate new technologies that you can learn and expand on top what you built in this guide.

include::{common-includes}/finish.adoc[]
